export { MethodsOfDefectSelect } from './ui/selects/MethodsOfDefectSelect'
export { TypeResultOfCheckSelect } from './ui/selects/TypeResultOfCheckSelect'
export { DefectStageSelect } from './ui/selects/DefectStageSelect'
export { DefectPrioritySelect } from './ui/selects/DefectPrioritySelect'

export { useMethodsOfDefectFromDict } from './model/selectors/defect/useMethodsOfDefectFromDict'
export { useTypeResultOfCheckFromDict } from './model/selectors/check/useTypeResultOfCheckFromDict'
export { useFixMethodTypeByIdFromDict } from './model/selectors/defect/useFixMethodTypeByIdFromDict'
export { useAgreementAnswerByDict } from './model/selectors/defect/useAgreementAnswerByDict'
export { useTypeManagerFromDict } from './model/selectors/manager/useTypeManagerFromDict'
export { useCheckStateByIdFromDict } from './model/selectors/check/useCheckStateByIdFromDict'
export { useCheckResultByIdFromDict } from './model/selectors/check/useCheckResultByIdFromDict'
export { useDefectStageFromDict } from './model/selectors/defect/useDefectStageFromDict'
export { usePriorityFromDict } from './model/selectors/defect/usePriorityFromDict'
export { useDefectStageByIdFromDict } from './model/selectors/defect/useDefectStageByIdFromDict'
export { useStateOfCheckFromDict } from './model/selectors/check/useStateOfCheckFromDict'
export { StateOfCheckSelect } from './ui/selects/StateOfCheckSelect'

export { $dict } from './model/get'
export { DictWrapper } from './ui/DictWrapper'
export * from './model/types'
