export const LOCAL_STORAGE_KEY_PAGE = 'PAGE'
export const LOCAL_STORAGE_KEY_FILTER = 'FILTER'
export const LOCAL_STORAGE_ADDITIONAL_TOKEN_KEY = 'ADDITIONAL_TOKEN'
export const LOCAL_STORAGE_BITRIX_TOKEN_KEY = 'BITRIX_TOKEN'

export type TLocalStorageKey = 'PAGE' | 'FILTER'
